name: maven

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: docker build image
        run: docker build .
      - name: Build docker image
        run: docker build -t inbaanbu1998/serverdeployed .
      - name: docker image tag
        run: docker tag serverdeployed inbaanbu1998/serverdeployed 
      - name: Publish image to docker hub
        run: docker push inbaanbu1998/serverdeployed
